config/routes.rb
Rails.application.routes.draw do
  get 'static/home'
  root to: 'static#home'

  get '/:phrase', to: "static#share"

  resources :phrases
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/phrase.rb
# == Schema Information
#
# Table name: phrases
#
#  id         :integer          not null, primary key
#  first_word :string
#  last_word  :string
#  position   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  slug       :string
#
# Indexes
#
#  index_phrases_on_slug  (slug) UNIQUE
#

class Phrase < ApplicationRecord

  before_validation :downcase_words

  validates :first_word, presence: true, uniqueness: { case_sensitive: false }
  validates :last_word, presence: true, uniqueness: { case_sensitive: false }

  validate :same_length
  validate :same_letters
  validate :unique_words
  validate :different_word
  validate :check_spelling

  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  def downcase_words
    self.first_word.downcase! \
      if self.first_word.present?

    self.last_word.downcase! \
      if self.last_word.present?
  end

  def same_length
    return unless \
      first_word.present? && last_word.present?

    return if first_word.length == last_word.length
    errors.add(:first_word, "must be same length")
  end

  def same_letters
    return unless \
      first_word.present? && last_word.present?

    first_characters = Set.new first_word.chars
    last_characters = Set.new last_word.chars

    return if first_characters == last_characters
    errors.add(:first_word, "must have same letters")
  end

  def unique_words
    return unless \
      first_word.present? && last_word.present?

    not_unique = !Phrase.where(first_word: last_word).empty?
    not_unique |= !Phrase.where(last_word: first_word).empty?

    return unless not_unique
    errors.add(:first_word, "must be unique word")
  end

  def different_word
    return unless \
      first_word.present? && last_word.present?

    return if first_word != last_word
    errors.add(:first_word, "must be a different word")
  end

  def check_spelling
    return unless \
      first_word.present? && last_word.present?

    has_real_word = [ false, false ]

    [ first_word, last_word ].each_with_index do |cur_word, cur_index|
      has_real_word[cur_index] ||= !WordNet::Lemma.find_all( @@lemmatizer.lemma(cur_word) ).empty?

      cur_files = [ "words/#{cur_word.chars.first}" ]
      cur_files += [ "custom", "20k" ]

      cur_files.each do |cur_file|
        has_real_word[cur_index] ||= \
          File.foreach("vendor/#{cur_file}.txt").any? {
            |l| l[cur_word]
          }
      end

    end

    return if has_real_word.all?
    errors.add(:first_word, "has a spelling error")
  end

  def slug_candidates
    [
      [:first_word, :last_word]
    ]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/phrases_controller.rb
class PhrasesController < ApplicationController
  before_action :set_phrase, only: [:show, :edit, :update, :destroy]

  # GET /phrases
  # GET /phrases.json
  def index
    @phrases = Phrase.all
  end

  # GET /phrases/1
  # GET /phrases/1.json
  def show
  end

  # GET /phrases/new
  def new
    @phrase = Phrase.new
  end

  # GET /phrases/1/edit
  def edit
  end

  # POST /phrases
  # POST /phrases.json
  def create
    @phrase = Phrase.new(phrase_params)

    respond_to do |format|
      if @phrase.save
        format.html { redirect_to @phrase, notice: 'Phrase was successfully created.' }
        format.json { render :show, status: :created, location: @phrase }
      else
        format.html { render :new }
        format.json { render json: @phrase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phrases/1
  # PATCH/PUT /phrases/1.json
  def update
    respond_to do |format|
      if @phrase.update(phrase_params)
        format.html { redirect_to @phrase, notice: 'Phrase was successfully updated.' }
        format.json { render :show, status: :ok, location: @phrase }
      else
        format.html { render :edit }
        format.json { render json: @phrase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phrases/1
  # DELETE /phrases/1.json
  def destroy
    @phrase.destroy
    respond_to do |format|
      format.html { redirect_to phrases_url, notice: 'Phrase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phrase
      @phrase = Phrase.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phrase_params
      params.require(:phrase).permit(:first_word, :last_word, :position)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def share
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phrases_helper.rb
module PhrasesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/_slides.html.erb
<div id="fullpage">

  <div class="section cs-first-section">

    <div class="cs-scroll-fix">

      <%= render 'layouts/title_card' %>

    </div>

    <div class="slide cs-first-slide">

      <%= render 'layouts/title_card' %>

    </div>

    <% Phrase.all.each_with_index do |cur_phrase, cur_index| %>

      <div class="slide <%= (cur_index+1).odd? ? "cs-odd-slide" : "cs-even-slide" %>">

        <div class="cs-box js-box cs-first-box">

          <div class="cs-word cs-first-word">
            <%= cur_phrase.first_word %>
          </div>

        </div>

        <div class="cs-box js-box cs-last-box">

          <div class="cs-word cs-last-word">
            <%= cur_phrase.last_word %>
          </div>

        </div>

      </div>

    <% end %>

  </div>

  <% Phrase.all.each_with_index do |cur_phrase, cur_index| %>

    <div class="section <%= (cur_index+1).odd? ? "cs-odd-section" : "cs-even-section" %>">

      <div class="slide <%= (cur_index+1).odd? ? "cs-odd-slide" : "cs-even-slide" %>">

        <div class="cs-box js-box cs-first-box">

          <div class="cs-word cs-first-word">
            <%= cur_phrase.first_word %>
          </div>

        </div>

        <div class="cs-box js-box cs-last-box">

          <div class="cs-word cs-last-word">
            <%= cur_phrase.last_word %>
          </div>

        </div>

      </div>

    </div>

  <% end %>

</div>

app/views/layouts/_title_card.html.erb
<div class="cs-title-card">

  <div class="cs-title-name cs-title-name__top">
    <a class="js-title-arrow js-prev-arrow">Hustling</a>
  </div>

  <div class="cs-title-name cs-title-name__bot">
    <a class="js-title-arrow js-next-arrow">Sunlight</a>
  </div>

  <div class="diagonal">
  </div>

  <div class="cs-info-box">

    <div class="cs-info-sub-box cs-info-sub-box__top">

      <div class="cs-info-text cs-hide-large">
        Scroll
      </div>

      <div class="cs-info-text cs-hide-small">
        Press
      </div>

    </div>

    <div class="cs-info-sub-box cs-info-sub-box__bot">

      <div class="cs-info-text cs-hide-large">
        <a class="cs-title-arrow js-title-arrow js-prev-arrow">↑</a><span class="cs-title-and">&amp;</span><a class="cs-title-arrow js-title-arrow js-next-arrow">↓</a>
      </div>

      <div class="cs-info-text cs-hide-small">
        <a class="cs-title-arrow js-title-arrow js-prev-arrow">←</a><span class="cs-title-and">&amp;</span><a class="cs-title-arrow js-title-arrow js-next-arrow">→</a>
      </div>

    </div>

  </div>

  <div class="cs-extra-box cs-email-box">

    <div class="cs-extra-sub-box">
      <div class="cs-extra-text">
        <a href="https://mail.google.com/mail/u/0/?view=cm&fs=1&to=dan@seg.al&su=Anagram+Suggestion&tf=1" target="_blank">
          <%= fa_icon "envelope" %>
        </a>
      </div>
    </div>

  </div>

  <div class="cs-extra-box cs-book-box">

    <div class="cs-extra-sub-box">
      <div class="cs-extra-text">
        <a href="https://www.printedmatter.org/catalog/45806/" target="_blank">
          <%= fa_icon "shopping-cart" %>
        </a>
      </div>
    </div>

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>

  <head>

    <!-- Global Site Tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-90729526-3"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments)};
      gtag('js', new Date());

      gtag('config', 'UA-90729526-3');
    </script>

    <title>Hustling Sunlight</title>

    <meta property="og:title" content="Anagrams in B&W" />
    <meta itemprop="name" content="Anagrams in B&W">
    <meta name="twitter:title" content="Anagrams in B&W">

    <meta property="og:url" content="http://www.hustlingsunlight.xyz/" />
    <meta property="og:site_name" content="Hustling Sunlight" />

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="keywords" content="hustling sunlight black white anagrams">
    <meta name="author" content="ahab io and matt bakkom">

    <meta name="description" content="A long sequence of anagrams in alternating black-against-white, white-against-black text and ground.">
    <meta itemprop="description" content="A long sequence of anagrams in alternating black-against-white, white-against-black text and ground.">
    <meta name="twitter:description" content="A long sequence of anagrams in alternating black-against-white, white-against-black text and ground.">
    <meta property="og:description" content="A long sequence of anagrams in alternating black-against-white, white-against-black text and ground." />

    <meta itemprop="image" content="http://www.hustlingsunlight.xyz/<%= yield(:image_url).blank? ? "hustling-sunlight" : yield(:image_url) %>.png">
    <meta name="twitter:image:src" content="http://www.hustlingsunlight.xyz/<%= yield(:image_url).blank? ? "hustling-sunlight" : yield(:image_url) %>.png">
    <meta property="og:image" content="http://www.hustlingsunlight.xyz/<%= yield(:image_url).blank? ? "hustling-sunlight" : yield(:image_url) %>.png" />

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Raleway:700" rel="stylesheet">

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-90729526-3', 'auto');
      ga('send', 'pageview');
    </script>

  </head>

  <body>

    <div class="cs-body">
      <%= yield %>
    </div>

    <%
      buttonDict = {
        "cs-hide-large" => "fa-lg",
        "cs-hide-small" => "fa-2x"
      }
    %>

    <% buttonDict.each do |cur_key, cur_value| %>
      <div class="cs-links <%= cur_key %>">
        <a onclick="goHome()" class="cs-link">
          <span class="fa-stack <%= cur_value %>">
            <i class="fa fa-square fa-stack-2x" style="color: #DDDDDD"></i>
            <i class="fa fa-home fa-stack-1x fa-inverse" style="color: #AAAAAA"></i>
          </span>
        </a>
        <a onclick="togglePlay()" class="cs-link" style="float: right;">
          <span class="fa-stack <%= cur_value %>">
            <i class="fa fa-square fa-stack-2x" style="color: #DDDDDD"></i>
            <i class="fa fa-play fa-stack-1x fa-inverse" style="color: #AAAAAA"></i>
          </span>
        </a>
        <br>
        <a onclick="copyToClipboard()" class="cs-link" style="float: right; margin-top: 1px;">
          <span class="fa-stack <%= cur_value %>">
            <i class="fa fa-square fa-stack-2x" style="color: #DDDDDD"></i>
            <i class="fa fa-share-alt fa-stack-1x fa-inverse" style="color: #AAAAAA"></i>
          </span>
        </a>
      </div>
    <% end %>

    <div class="cs-alert cs-alert-primary cs-zero-opacity">
       copied url
    </div>

    <div class="cs-alert cs-alert-inverse cs-zero-opacity">
       copied url
    </div>

    <div class="cs-loader diagonal">
      <div class="loader"></div>
    </div>

  </body>

</html>

app/views/phrases/_form.html.erb
<%= form_with(model: phrase, local: true) do |form| %>
  <% if phrase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(phrase.errors.count, "error") %> prohibited this phrase from being saved:</h2>

      <ul>
      <% phrase.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_word %>
    <%= form.text_field :first_word, id: :phrase_first_word %>
  </div>

  <div class="field">
    <%= form.label :last_word %>
    <%= form.text_field :last_word, id: :phrase_last_word %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.number_field :position, id: :phrase_position %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/phrases/edit.html.erb
<h1>Editing Phrase</h1>

<%= render 'form', phrase: @phrase %>

<%= link_to 'Show', @phrase %> |
<%= link_to 'Back', phrases_path %>

app/views/phrases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Phrases</h1>

<table>
  <thead>
    <tr>
      <th>First word</th>
      <th>Last word</th>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @phrases.each do |phrase| %>
      <tr>
        <td><%= phrase.first_word %></td>
        <td><%= phrase.last_word %></td>
        <td><%= phrase.position %></td>
        <td><%= link_to 'Show', phrase %></td>
        <td><%= link_to 'Edit', edit_phrase_path(phrase) %></td>
        <td><%= link_to 'Destroy', phrase, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Phrase', new_phrase_path %>

app/views/phrases/new.html.erb
<h1>New Phrase</h1>

<%= render 'form', phrase: @phrase %>

<%= link_to 'Back', phrases_path %>

app/views/phrases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First word:</strong>
  <%= @phrase.first_word %>
</p>

<p>
  <strong>Last word:</strong>
  <%= @phrase.last_word %>
</p>

<p>
  <strong>Position:</strong>
  <%= @phrase.position %>
</p>

<%= link_to 'Edit', edit_phrase_path(@phrase) %> |
<%= link_to 'Back', phrases_path %>